apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pg-claim
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.4-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
        volumeMounts:
          - mountPath: /data/db
            name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pg-claim    

