# This is a basic workflow to help you get started with Actions

name: Deploy container to DO Server in Production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ docker-aws ]
  pull_request:
    branches: [ docker-aws ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Install DigitalOcean Controller
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Setup Docker Builder
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            registry.digitalocean.com/docker-nodejs-deployment-strategies/api:latest
            registry.digitalocean.com/docker-nodejs-deployment-strategies/api:sha-${{ github.sha }}

  deploy-api:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy api to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DO_API_HOST }}
          username: root
          key: ${{ secrets.DO_API_KEY }}
          port: 22
          script: |
            doctl registry login --expiry-seconds 180
            docker pull registry.digitalocean.com/docker-nodejs-deployment-strategies/api:latest

            echo 'Starting server instance'
            docker run -d \
              --restart always \
              -p 0.0.0.0:80:8080
              --name api \
              registry.digitalocean.com/docker-nodejs-deployment-strategies/api:latest